<?php declare(strict_types=1);

namespace Lkrms\Time\Sync\Contract;

use Lkrms\Iterator\Contract\FluentIteratorInterface;
use Lkrms\Sync\Contract\ISyncContext;
use Lkrms\Sync\Contract\ISyncProvider;
use Lkrms\Time\Sync\Entity\Client;

/**
 * Syncs Client objects with a backend
 *
 * @method Client getClient(ISyncContext $ctx, int|string|null $id)
 * @method FluentIteratorInterface<array-key,Client> getClients(ISyncContext $ctx)
 *
 * @generated by lk-util
 * @salient-generate-command generate sync provider --magic --op='get,get-list' 'Lkrms\Time\Sync\Entity\Client'
 */
interface ProvidesClient extends ISyncProvider {}
