<?php declare(strict_types=1);

namespace Lkrms\Time\Sync\Contract;

use Lkrms\Time\Sync\Entity\TimeEntry;
use Salient\Contract\Iterator\FluentIteratorInterface;
use Salient\Contract\Sync\SyncContextInterface;
use Salient\Contract\Sync\SyncProviderInterface;

/**
 * Syncs TimeEntry objects with a backend
 *
 * @method TimeEntry getTimeEntry(SyncContextInterface $ctx, int|string|null $id)
 * @method TimeEntry updateTimeEntry(SyncContextInterface $ctx, TimeEntry $timeEntry)
 * @method FluentIteratorInterface<array-key,TimeEntry> getTimeEntries(SyncContextInterface $ctx)
 *
 * @generated by lk-util
 * @salient-generate-command generate sync provider --magic --op='get,update,get-list' 'Lkrms\Time\Sync\Entity\TimeEntry'
 */
interface ProvidesTimeEntry extends SyncProviderInterface {}
