<?php declare(strict_types=1);

namespace Lkrms\Time\Sync\Contract;

use Lkrms\Time\Sync\Entity\Tenant;
use Salient\Contract\Iterator\FluentIteratorInterface;
use Salient\Contract\Sync\SyncContextInterface;
use Salient\Contract\Sync\SyncProviderInterface;

/**
 * Syncs Tenant objects with a backend
 *
 * @method Tenant getTenant(SyncContextInterface $ctx, int|string|null $id)
 * @method FluentIteratorInterface<array-key,Tenant> getTenants(SyncContextInterface $ctx)
 *
 * @generated by lk-util
 * @salient-generate-command generate sync provider --magic --op='get,get-list' 'Lkrms\Time\Sync\Entity\Tenant'
 */
interface ProvidesTenant extends SyncProviderInterface {}
