<?php declare(strict_types=1);

namespace Lkrms\Time\Sync\Contract;

use Lkrms\Time\Sync\Entity\Client;
use Salient\Contract\Iterator\FluentIteratorInterface;
use Salient\Contract\Sync\SyncContextInterface;
use Salient\Contract\Sync\SyncProviderInterface;

/**
 * Syncs Client objects with a backend
 *
 * @method Client getClient(SyncContextInterface $ctx, int|string|null $id)
 * @method FluentIteratorInterface<array-key,Client> getClients(SyncContextInterface $ctx)
 *
 * @generated by lk-util
 * @salient-generate-command generate sync provider --magic --op='get,get-list' 'Lkrms\Time\Sync\Entity\Client'
 */
interface ProvidesClient extends SyncProviderInterface {}
