<?php declare(strict_types=1);

namespace Lkrms\Time\Sync\Contract;

use Lkrms\Iterator\Contract\FluentIteratorInterface;
use Lkrms\Sync\Contract\ISyncContext;
use Lkrms\Sync\Contract\ISyncProvider;
use Lkrms\Time\Sync\Entity\Invoice;

/**
 * Syncs Invoice objects with a backend
 *
 * @method Invoice createInvoice(ISyncContext $ctx, Invoice $invoice)
 * @method Invoice getInvoice(ISyncContext $ctx, int|string|null $id)
 * @method FluentIteratorInterface<array-key,Invoice> getInvoices(ISyncContext $ctx)
 *
 * @generated by lk-util
 * @salient-generate-command generate sync provider --magic --op='create,get,get-list' 'Lkrms\Time\Sync\Entity\Invoice'
 */
interface ProvidesInvoice extends ISyncProvider {}
