<?php declare(strict_types=1);

namespace Lkrms\Time\Sync\Contract;

use Lkrms\Time\Sync\Entity\User;
use Salient\Contract\Iterator\FluentIteratorInterface;
use Salient\Contract\Sync\SyncContextInterface;
use Salient\Contract\Sync\SyncProviderInterface;

/**
 * Syncs User objects with a backend
 *
 * @method User getUser(SyncContextInterface $ctx, int|string|null $id)
 * @method FluentIteratorInterface<array-key,User> getUsers(SyncContextInterface $ctx)
 *
 * @generated by lk-util
 * @salient-generate-command generate sync provider --magic --op='get,get-list' 'Lkrms\Time\Sync\Entity\User'
 */
interface ProvidesUser extends SyncProviderInterface {}
