<?php declare(strict_types=1);

namespace Lkrms\Time\Sync\Contract;

use Lkrms\Time\Sync\Entity\Project;
use Salient\Contract\Iterator\FluentIteratorInterface;
use Salient\Contract\Sync\SyncContextInterface;
use Salient\Contract\Sync\SyncProviderInterface;

/**
 * Syncs Project objects with a backend
 *
 * @method Project getProject(SyncContextInterface $ctx, int|string|null $id)
 * @method FluentIteratorInterface<array-key,Project> getProjects(SyncContextInterface $ctx)
 *
 * @generated by lk-util
 * @salient-generate-command generate sync provider --magic --op='get,get-list' 'Lkrms\Time\Sync\Entity\Project'
 */
interface ProvidesProject extends SyncProviderInterface {}
