<?php declare(strict_types=1);

namespace Lkrms\Time\Sync\Contract;

use Lkrms\Time\Sync\Entity\Task;
use Salient\Contract\Iterator\FluentIteratorInterface;
use Salient\Contract\Sync\SyncContextInterface;
use Salient\Contract\Sync\SyncProviderInterface;

/**
 * Syncs Task objects with a backend
 *
 * @method Task getTask(SyncContextInterface $ctx, int|string|null $id)
 * @method FluentIteratorInterface<array-key,Task> getTasks(SyncContextInterface $ctx)
 *
 * @generated by lk-util
 * @salient-generate-command generate sync provider --magic --op='get,get-list' 'Lkrms\Time\Sync\Entity\Task'
 */
interface ProvidesTask extends SyncProviderInterface {}
