<?php declare(strict_types=1);

namespace Lkrms\Time\Entity\Provider;

use Lkrms\Support\Iterator\Contract\FluentIteratorInterface;
use Lkrms\Sync\Contract\ISyncContext;
use Lkrms\Sync\Contract\ISyncProvider;
use Lkrms\Time\Entity\Task;

/**
 * Syncs Task objects with a backend
 *
 * @method Task getTask(ISyncContext $ctx, int|string|null $id)
 * @method FluentIteratorInterface<array-key,Task> getTasks(ISyncContext $ctx)
 *
 * @generated by lk-util
 * @salient-generate-command generate sync provider --magic --op='get,get-list' 'Lkrms\Time\Entity\Task'
 */
interface TaskProvider extends ISyncProvider {}
