<?php declare(strict_types=1);

namespace Lkrms\Time\Entity\Provider;

use Lkrms\Iterator\Contract\FluentIteratorInterface;
use Lkrms\Sync\Contract\ISyncContext;
use Lkrms\Time\Entity\TimeEntry;

/**
 * Syncs TimeEntry objects with a backend
 *
 * @method TimeEntry getTimeEntry(ISyncContext $ctx, int|string|null $id)
 * @method TimeEntry updateTimeEntry(ISyncContext $ctx, TimeEntry $timeEntry)
 * @method FluentIteratorInterface<array-key,TimeEntry> getTimeEntries(ISyncContext $ctx)
 * @method FluentIteratorInterface<array-key,TimeEntry> updateTimeEntries(ISyncContext $ctx, iterable<TimeEntry> $timeEntries)
 *
 * @generated by lk-util
 * @salient-generate-command generate sync provider --extend='Lkrms\Time\Entity\Provider\ClientProvider,Lkrms\Time\Entity\Provider\ProjectProvider,Lkrms\Time\Entity\Provider\TaskProvider,Lkrms\Time\Entity\Provider\UserProvider' --magic --op='get,update,get-list,update-list' 'Lkrms\Time\Entity\TimeEntry'
 */
interface TimeEntryProvider extends ClientProvider, ProjectProvider, TaskProvider, UserProvider {}
